# -*- coding: utf-8 -*-
"""the new york times.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eQ7N83ESPfkDitoWwiqrXb-snsQ103Zk
"""

import requests
from bs4 import BeautifulSoup

url = "https://www.nytimes.com/2023/11/10/business/moodys-negative-credit-outlook.html?searchResultPosition=1"
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"

headers = {'User-Agent': user_agent}
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser')

    # 기사 제목 추출
    title = soup.find('h1', class_='css-1l8buln e1h9rw200')
    title_text = title.text.strip() if title else ""

    # 기사 날짜 추출
    date_element = soup.find('time', class_='css-1g7pp1u e16638kd0')
    date = date_element['datetime'].split("T")[0] if date_element else ""

    # 기사 내용 추출
    article_content = soup.find('div', class_='css-53u6y8')
    paragraphs = article_content.find_all('p') if article_content else []
    article_text = "\n".join(paragraph.get_text() for paragraph in paragraphs)

    # 결과 출력
    print("Title:", title_text)
    print("Date:", date)
    print("Contents:")
    print(article_text)

else:
    print("HTTP 요청에 실패했습니다. 상태 코드:", response.status_code)

import requests
import json
from datetime import datetime

headers = {
    'authority': 'samizdat-graphql.nytimes.com',
    'method': 'POST',
    'path': '/graphql/v2',
    'scheme': 'https',
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'ko,en;q=0.9,en-US;q=0.8',
    'Content-Length': '424',
    'Content-Type': 'application/json',
    'Cookie': 'nyt-a=J4T9OgaEqIkyaay6LKCM-K; nyt-purr=cfhhcfhhhukfhufs; ...',
    'Nyt-App-Type': 'project-vi',
    'Nyt-App-Version': '0.0.5',
    'Nyt-Token': 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs+/oUCTBmD/cLdmcecrnBMHiU/pxQCn2DDyaPKUOXxi4p0uUSZQzsuq1pJ1m5z1i0YGPd1U1OeGHAChWtqoxC7bFMCXcwnE1oyui9G1uobgpm1GdhtwkR7ta7akVTcsF8zxiXx7DNXIPd2nIJFH83rmkZueKrC4JVaNzjvD+Z03piLn5bHWU6+w+rA+kyJtGgZNTXKyPh6EC6o5N+rknNMG5+CdTq35p8f99WjFawSvYgP9V64kgckbTbtdJ6YhVP58TnuYgr12urtwnIqWP9KSJ1e5vmgf3tunMqWNm6+AnsqNj8mCLdCuc5cEB74CwUeQcP2HQQmbCddBy2y0mEwIDAQAB',
    'Origin': 'https://www.nytimes.com',
    'Referer': 'https://www.nytimes.com/',
    'Sec-Ch-Ua': 'Microsoft Edge";v="119", "Chromium";v="119", "Not?A_Brand";v="24"',
    'Sec-Ch-Ua-Mobile': '?0',
    'Sec-Ch-Ua-Platform': '"Windows"',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0',
    'X-Nyt-Internal-Meter-Override': 'undefined'
}

data = {
    "operationName": "SearchRootQuery",
    "variables": {
        "first": 10,
        "sort": "newest",
        "text": "interest rate",
        "filterQuery": "((type: \"article\"))",
        "sectionFacetFilterQuery": "((type: \"article\"))",
        "typeFacetFilterQuery": "",
        "sectionFacetActive": True,
        "typeFacetActive": True,
        "cursor": "YXJyYXljb25uZWN0aW9uOjk="
    },
    "extensions": {
        "persistedQuery": {
            "version": 1,
            "sha256Hash": "57637487214907d9fded37e092695fcc12dcf8d819b36ae657056d8f42151c89"
        }
    }
}

response = requests.post('https://samizdat-graphql.nytimes.com/graphql/v2', headers=headers, json=data)


json_data = response.json()

articles = json_data.get("data", {}).get("search", {}).get("hits", {}).get("edges", [])

for article in articles:
        node = article.get("node", {})
        if node and node.get("__typename") == "Article":

            headline = node.get("creativeWorkHeadline", {}).get("default", "")
            date = node.get("firstPublished", "")
            summary = node.get("creativeWorkSummary", "")
            formatted_date = datetime.strptime(date, "%Y-%m-%dT%H:%M:%S.%fZ").strftime("%Y-%m-%d")

            print("제목:", headline)
            print("날짜:", formatted_date)
            print("요약:", summary)
            print("\n")

import requests
from bs4 import BeautifulSoup
from datetime import datetime

headers = {
    'authority': 'samizdat-graphql.nytimes.com',
    'method': 'POST',
    'path': '/graphql/v2',
    'scheme': 'https',
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'ko,en;q=0.9,en-US;q=0.8',
    'Content-Length': '424',
    'Content-Type': 'application/json',
    'Cookie': 'nyt-a=J4T9OgaEqIkyaay6LKCM-K; nyt-purr=cfhhcfhhhukfhufs; ...',
    'Nyt-App-Type': 'project-vi',
    'Nyt-App-Version': '0.0.5',
    'Nyt-Token': 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs+/oUCTBmD/cLdmcecrnBMHiU/pxQCn2DDyaPKUOXxi4p0uUSZQzsuq1pJ1m5z1i0YGPd1U1OeGHAChWtqoxC7bFMCXcwnE1oyui9G1uobgpm1GdhtwkR7ta7akVTcsF8zxiXx7DNXIPd2nIJFH83rmkZueKrC4JVaNzjvD+Z03piLn5bHWU6+w+rA+kyJtGgZNTXKyPh6EC6o5N+rknNMG5+CdTq35p8f99WjFawSvYgP9V64kgckbTbtdJ6YhVP58TnuYgr12urtwnIqWP9KSJ1e5vmgf3tunMqWNm6+AnsqNj8mCLdCuc5cEB74CwUeQcP2HQQmbCddBy2y0mEwIDAQAB',
    'Origin': 'https://www.nytimes.com',
    'Referer': 'https://www.nytimes.com/',
    'Sec-Ch-Ua': 'Microsoft Edge";v="119", "Chromium";v="119", "Not?A_Brand";v="24"',
    'Sec-Ch-Ua-Mobile': '?0',
    'Sec-Ch-Ua-Platform': '"Windows"',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0',
    'X-Nyt-Internal-Meter-Override': 'undefined'
}

data = {
    "operationName": "SearchRootQuery",
    "variables": {
        "first": 10,
        "sort": "newest",
        "text": "interest rate",
        "filterQuery": "((type: \"article\"))",
        "sectionFacetFilterQuery": "((type: \"article\"))",
        "typeFacetFilterQuery": "",
        "sectionFacetActive": True,
        "typeFacetActive": True,
        "cursor": "YXJyYXljb25uZWN0aW9uOjk="
    },
    "extensions": {
        "persistedQuery": {
            "version": 1,
            "sha256Hash": "57637487214907d9fded37e092695fcc12dcf8d819b36ae657056d8f42151c89"
        }
    }
}

response = requests.post('https://samizdat-graphql.nytimes.com/graphql/v2', headers=headers, json=data)

json_data = response.json()

articles = json_data.get("data", {}).get("search", {}).get("hits", {}).get("edges", [])



for article in articles:
    node = article.get("node", {})
    if node and node.get("__typename") == "Article":
        headline = node.get("creativeWorkHeadline", {}).get("default", "")
        date = node.get("firstPublished", "")
        summary = node.get("creativeWorkSummary", "")
        formatted_date = datetime.strptime(date, "%Y-%m-%dT%H:%M:%S.%fZ").strftime("%Y-%m-%d")


        print("날짜:", formatted_date)
        print("제목:", headline)
        print("요약:", summary)

        # 기사 URL 추출
        article_url = node.get("url", "")

        # BeautifulSoup을 사용하여 기사 내용 스크래핑
        if article_url:
            user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
            headers = {'User-Agent': user_agent}
            response = requests.get(article_url, headers=headers)

            if response.status_code == 200:
                soup = BeautifulSoup(response.text, 'html.parser')

                # 기사 내용을 포함한 모든 단락 추출
                paragraphs = soup.find_all('p')
                article_text = "\n".join(paragraph.get_text() for paragraph in paragraphs)

                # 결과 출력
                print("기사 내용:")
                print(article_text)
                print("\n")
            else:
                print(f"HTTP 요청에 실패했습니다. 상태 코드: {response.status_code}")
        else:
            print("기사 URL을 찾을 수 없습니다.")