# -*- coding: utf-8 -*-
"""csv저장 및 합치기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1agJHy2-0Sql9rH_beUxpamb7MbXbBdwr

## CSV파일로 저장하기
"""

import csv

def text_to_csv(input_text, output_csv):
    # 텍스트 파일에서 데이터 읽어오기
    with open(input_text, 'r') as txt_file:
        lines = txt_file.readlines()

    # CSV 파일로 데이터 쓰기
    with open(output_csv, 'w', newline='') as csv_file:
        csv_writer = csv.writer(csv_file)

        # 각 줄을 그대로 CSV 파일에 쓰기
        for line in lines:
            csv_writer.writerow([line.rstrip('\n')])

    print(f'{input_text} 파일이 {output_csv} 파일로 성공적으로 변환되었습니다.')

# 파일 경로 및 이름 지정
input_text_path = '/content/drive/MyDrive/미국금리/민채/FOMC인터뷰/23인터뷰/2023인터뷰.txt'
output_csv_path = '/content/drive/MyDrive/미국금리/민채/FOMC인터뷰/2023인터뷰.cvs'

# 함수 호출
text_to_csv(input_text_path, output_csv_path)

from google.colab import drive
drive.mount('/content/drive')



"""## 파일 합치기"""

import csv
import os

def merge_csv_files(input_folder, output_csv):
    # 출력 파일을 쓰기 모드로 열기
    with open(output_csv, 'w', newline='', encoding='utf-8') as out_csv:
        csv_writer = csv.writer(out_csv)

        # 입력 폴더 내의 모든 CSV 파일에 대해 반복
        for filename in os.listdir(input_folder):
            if filename.endswith('.csv'):
                csv_filepath = os.path.join(input_folder, filename)

                # 현재 CSV 파일을 읽어오기
                with open(csv_filepath, 'r', newline='', encoding='utf-8') as in_csv:
                    csv_reader = csv.reader(in_csv)

                    # 각 행을 출력 파일에 쓰기
                    for row in csv_reader:
                        csv_writer.writerow(row)

    print(f'{input_folder} 내의 CSV 파일이 {output_csv} 파일로 성공적으로 합쳐졌습니다.')

# 폴더 경로 및 출력 파일 이름 지정
input_folder_path = '/content/drive/MyDrive/미국금리/민채/FOMC인터뷰/18인터뷰'
output_csv_path = '/content/drive/MyDrive/미국금리/민채/FOMC인터뷰/18-1.csv'

# 함수 호출
merge_csv_files(input_folder_path, output_csv_path)





"""## 파일 불러오기"""

import csv

def read_csv_file(file_path):
    with open(file_path, 'r', newline='', encoding='utf-8') as csv_file:
        csv_reader = csv.reader(csv_file)

        # CSV 파일의 각 행에 대해 반복
        for row in csv_reader:
            print(row)

# CSV 파일 경로 지정
csv_file_path = '/content/drive/MyDrive/미국금리/민채/FOMC연설/18.csv'

# 함수 호출
read_csv_file(csv_file_path)